behavior_server:
  ros__parameters:
    local_costmap_topic: local_costmap/costmap_raw
    local_footprint_topic: local_costmap/published_footprint
    global_costmap_topic: global_costmap/costmap_raw
    global_footprint_topic: global_costmap/published_footprint
    cycle_frequency: 1000.0
    behavior_plugins: ["spin","backup", "drive_on_heading", "wait"] # 
    spin:
      plugin: "nav2_behaviors/Spin" # In Iron and older versions, "/" was used instead of "::"
    backup:
      plugin: "nav2_behaviors/BackUp" # In Iron and older versions, "/" was used instead of "::"
      minimum_speed: 4.0

    drive_on_heading:
      plugin: "nav2_behaviors/DriveOnHeading" # In Iron and older versions, "/" was used instead of "::"
      minimum_speed: 1.57
      
    wait:
      plugin: "nav2_behaviors/Wait" # In Iron and older versions, "/" was used instead of "::"
    
    local_frame: map
    global_frame: map
    robot_base_frame: os_sensor
    transform_tolerance: 3.0
    simulate_ahead_time: 2.0
    max_rotational_vel: 0.1
    min_rotational_vel: 0.0 
    rotational_acc_lim: 0.05
    enable_stamped_cmd_vel: false  # default false in Jazzy or older
    
    