global_costmap: 
  global_costmap:
    ros__parameters:
        global_frame: "map"
        robot_base_frame: "velodyne"
        update_frequency: 10.0
        publish_frequency: 5.0
        rolling_window: true
        use_sim_time: False
        resolution: 0.05
        always_send_full_costmap: true
        height: 250
        width: 250
        transform_tolerance: 5.0
        track_unknown_space: false
        # footprint:
        #   - [-1.2, -0.60]
        #   - [-1.2, 0.60]
        #   - [1.2, 0.6]
        #   - [1.2, -0.6]
        footprint: "[[-3.1,-1.0], [-3.1, 1.0], [1.6, 1.0], [1.6,-1.0]]"  # Define your car's footprint here [[-2.31, -0.95], [-2.31,  0.95], [2.31,  0.95], [2.31, -0.95]]
  
        # robot_radius: 2.5
  
        plugins: ["static_layer", "stvl_layer", "inflation_layer"]
          #  - "stvl_layer", , "inflation_layer"
          # - {name: static_layer, type: "costmap_2d::StaticLayer"}
          
          # - {name: spatio_temporal_voxel_layer, type: "spatio_temporal_voxel_layer/SpatioTemporalVoxelLayer"}
          # - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
  
        static_layer:
          plugin: "nav2_costmap_2d::StaticLayer"
          map_topic: "/map"
          subscribe_to_updates: true
  
        
        stvl_layer:
          plugin: "spatio_temporal_voxel_layer/SpatioTemporalVoxelLayer"
          enabled:                  true
          voxel_decay:              3.0  # seconds if linear, e^n if exponential
          decay_model:              0     # 0=linear, 1=exponential, -1=persistent
          voxel_size:               0.6 # meters
          track_unknown_space:      false  # default space is unknown
          mark_threshold:           0     # voxel height
          update_footprint_enabled: true
          combination_method:       1     # 1=max, 0=override
          origin_z:                 0.0   # meters
          publish_voxel_map:        true # default off
          transform_tolerance:      10.2   # seconds
          mapping_mode:             false # default off, saves map not for navigation
          map_save_duration:        60.0  # default 60s, how often to autosave
          observation_sources:      pointcloud
          pointcloud:
            data_type: PointCloud2
            topic: /ouster/points/non_ground
            marking: true
            clearing: true
            obstacle_range: 50.0
            min_obstacle_height: 0.0
            max_obstacle_height: 2.0
            expected_update_rate: 0.0
            observation_persistence: 0.0
            inf_is_valid: false
            filter: "voxel"
            voxel_min_points: 0
            clear_after_reading: true
            max_z: 10.0
            min_z: 0.0
            vertical_fov_angle: 1.5708
            horizontal_fov_angle: 6.28319
            decay_acceleration: 30.0
            model_type: 1             # default 0, model type for frustum. 0=depth camera, 1=3d lidar like VLP16 or similar
          
        inflation_layer:
          plugin: "nav2_costmap_2d::InflationLayer"
          inflation_radius: 1.01
          cost_scaling_factor: 10.0
  