local_costmap:
  local_costmap: 
    ros__parameters:
       global_frame: "map"
       robot_base_frame: "velodyne"
       update_frequency: 10.0
       publish_frequency: 5.0
       rolling_window: true
       transform_tolerance: 10.0
       width: 50
       height: 50
       resolution: 0.1
       # footprint:
       #   - [-1.2, -0.60]
       #   - [-1.2, 0.60]
       #   - [1.2, 0.6]
       #   - [1.2, -0.6]
       # robot_radius: 2.73
         # Front-left

       
       footprint: "[[-1.55,-0.95], [-1.55, 0.95], [3.07, 0.95], [3.07,-0.95]]"  # Define your car's footprint here #carla fp:[(-2.6188, -0.9649), (-2.6188,  0.9649), ( 2.6188,  0.9649), ( 2.6188, -0.9649)]
       
       plugins: [ "voxel_layer", "inflation_layer"]
       
        # , "inflation_layer"
       voxel_layer:
          plugin: "spatio_temporal_voxel_layer/SpatioTemporalVoxelLayer"
          enabled:                  true
          voxel_decay:              3.0  # seconds if linear, e^n if exponential
          decay_model:              0     # 0=linear, 1=exponential, -1=persistent
          voxel_size:               0.6 # meters
          track_unknown_space:      false  # default space is unknown
          mark_threshold:           0     # voxel height
          update_footprint_enabled: true
          combination_method:       1     # 1=max, 0=override
          origin_z:                 0.0   # meters
          publish_voxel_map:        true # default off
          transform_tolerance:      10.2   # seconds
          mapping_mode:             false # default off, saves map not for navigation
          map_save_duration:        60.0  # default 60s, how often to autosave
          observation_sources:      pointcloud
          pointcloud:
            data_type: PointCloud2
            topic: /velodyne_points/non_ground
            marking: true
            clearing: true
            obstacle_range: 50.0
            min_obstacle_height: 0.0
            max_obstacle_height: 2.0
            expected_update_rate: 0.0
            observation_persistence: 0.0
            inf_is_valid: false
            filter: "voxel"
            voxel_min_points: 0
            clear_after_reading: true
            max_z: 10.0
            min_z: 0.0
            vertical_fov_angle: 1.5708
            horizontal_fov_angle: 6.28319
            decay_acceleration: 30.0
            model_type: 1             # default 0, model type for frustum. 0=depth camera, 1=3d lidar like VLP16 or similar
          
        # plugin: "nav2_costmap_2d::VoxelLayer"
        # enabled: True
        # footprint_clearing_enabled: True
        # publish_voxel_map: True
        # origin_z: 0.0
        # z_resolution: 0.9
        # z_voxels: 16
        # max_obstacle_height: 1.5
        # mark_threshold: 0
        # observation_sources: scan
        # scan:
        #   topic: /ouster/points/non_ground 
        #   max_obstacle_height: 1.5
        #   observation_persistence: 0.0
        #   expected_update_rate: 0.0
        #   min_obstacle_height: 0.0
        #   max_obstacle_height: 1.5
        #   inf_is_valid: False

        #   clearing: True
        #   marking: True
        #   data_type: "PointCloud2"
        #   raytrace_max_range: 30.0
        #   raytrace_min_range: 0.1
        #   obstacle_max_range: 30.5
        #   obstacle_min_range: 0.1
      
      
        
        
         
       inflation_layer:
         plugin: "nav2_costmap_2d::InflationLayer"
         inflation_radius: 1.01
         cost_scaling_factor: 10.0
